# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: maeddes/gitpod:full

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
