version: '3.8'

services:
  spring-backendx:
    image: springbackend:v0.1
    depends_on:
      - postgresx
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hftdb  # Updated to use the hostname 'postgres' instead of 'localhost'
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - hftnet

  postgresx:
    image: postgres:latest
    environment:
      POSTGRES_DB: hftdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - hftnet

  flask-frontendx:
    image: flaskfrontend:v0.1
    ports:
      - "5001:5000"
    environment:
      API_BASE_URL: http://spring-backendx:8090  # Update with the actual URL of your Spring Boot app
    depends_on:
      - spring-backendx
    networks:
      - hftnet

networks:
  hftnet:  # Define the existing network
    external: true  # Specify
