# Use a base image with Java 11 (you can choose a different version if needed)
FROM eclipse-temurin:21

# Set the working directory in the container
WORKDIR /app

ADD 

# Copy the JAR file (change the JAR filename as needed)
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar



# Expose the port that your Spring Boot application is running on (default is 8080)
EXPOSE 8090

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "app.jar"]
