openapi: 3.0.1
info:
  title: Strings API
  version: 1.0.0
paths:
  /api/strings:
    get:
      summary: Get all strings
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/strings/{originalString}/{newString}:
    put:
      summary: Update a string by ID
      parameters:
        - in: path
          name: originalString
          required: true
          schema:
            type: string
        - in: path
          name: newString
          required: true
          schema:
            type: string
  /api/strings/{string}:
    get:
      summary: Get a string by ID
      parameters:
        - in: path
          name: string
          required: true
          schema:
            type: string
    delete:
      summary: Delete a string by ID
      parameters:
        - in: path
          name: string
          required: true
          schema:
            type: string
    post:
      summary: Create a new string
      parameters:
        - in: query
          name: newString
          required: true
          schema:
            type: string